name: SecondCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "This is the second workflow!"

      - name: Run a multi-line script
        run: |
          echo "You can customize this workflow"
          echo "to perform different tasks than the first one."